name: three
version: 0.2.6
authors:
- Robert Silverton <rob.silverton@gmail.com>
- Nelson Silva <nelson.silva@inevo.pt>
- Adam Singer <financeCoding@gmail.com>
- John <jwbito@gmail.com>
- Anders Forsell http://aforsell.blogspot.com/
- Christopher Grabowski https://github.com/cgrabowski
description: A port of the three.js JavaScript 3D engine to Dart.
homepage: http://threedart.github.com/three.dart/
environment:
  sdk: '>2.0.0'
dependencies:
  vector_math: '>=1.3.5'
  # datgui:
  #   git: git://github.com/cgrabowski/datgui.git
  # stats:
  #   git: git://github.com/Dartist/stats.dart.git
dev_dependencies:
  build_runner: any
  build_web_compilers: any
  convert: ^2.0.1
